# Output the Project ID for use in other configurations
output "project_id" {
  value       = coolify_project.production_infrastructure.id
  description = "The UUID generated by Coolify for the production infrastructure project"
}